### ISSUE TITLE
整理文档

### ISSUE THREAD

**Issue by withlin** [CanalClient/canal-go#23]
as title

**Comment by crazelee** [comment]
将message.entries打印出来是这样的模样，这是什么问题呢，不能可视化的看到操作语句
[]com_alibaba_otter_canal_protocol.Entry{com_alibaba_otter_canal_protocol.Entry{Header:(*com_alibaba_otter_canal_protocol.Header)(0xc00010a000), EntryTypePresent:(*com_alibaba_otter_canal_protocol.Entry_EntryType)(0xc0000f8044), StoreValue:[]uint8{0x20, 0xb}, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, com_alibaba_otter_canal_protocol.Entry{Header:(*com_alibaba_otter_canal_protocol.Header)(0xc00010a0e0), EntryTypePresent:(*com_alibaba_otter_canal_protocol.Entry_EntryType)(0xc0000f8070), StoreValue:[]uint8{0x12, 0x4, 0x31, 0x38, 0x38, 0x30}, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}}
