### ISSUE TITLE
客户端不支持canal 1.1.2

### ISSUE THREAD

**Issue by ddonline** [CanalClient/canal-go#24]
对canal 1.1.0 解析正常，升级canal 1.1.2 后，获取不到数据，无报错
是哪里需要修改一下么？

**Comment by WithLin** [comment]
我有空 测试下,测试回复您。

**Comment by ddonline** [comment]
好的 谢谢  感觉是1.1.2的调用方式和1.1.0不一样

**Comment by WithLin** [comment]
我这边测试没有问题，是否是你的配置不对？

**Comment by WithLin** [comment]
我先关闭 issue了 有什么问题 再打开。
