### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by lily-lee** [CanalClient/canal-go#30]
```
go: github.com/CanalSharp/canal-go@v0.0.0-20190218034808-a31b8dbd3d50: parsing go.mod: unexpected module path "github.com/CanalClient/canal-go"
```

**Comment by laughmaker** [comment]
> ```
> go: github.com/CanalSharp/canal-go@v0.0.0-20190218034808-a31b8dbd3d50: parsing go.mod: unexpected module path "github.com/CanalClient/canal-go"
> ```

同样的问题，你解决了吗？

**Comment by laughmaker** [comment]
go get github.com/CanalClient/canal-go
看了下Mod里是这个名字，两个 名字不一样，用这个名字就好了

**Comment by withlin** [comment]
更新了下 文档。您看看
