### ISSUE TITLE
客户端解码问题

### ISSUE THREAD

**Issue by wyhisphper** [CanalClient/canal-go#6]
cancal用的是canal/canal-server: v1.1.0镜像，客户端一直没有成功
遇到两个问题
第一个：在get的时候解码报错了，偶现
Fatal error: proto: Messages: illegal tag 0 (wire type 0)exit status 1

第二个：如果get成功了，就一定会报这个错误
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5222d2]

goroutine 1 [running]:
github.com/CanalClient/canal-go/protocol.(*RowChange).Reset(0x0)
        /home/wenyuanhao/goworkspace/src/github.com/CanalClient/canal-go/protocol/EntryProtocol.pb.go:917 +0x22
github.com/CanalSharp/canal-go/vendor/github.com/golang/protobuf/proto.Unmarshal(0xc420016240, 0x17, 0x20, 0x6481c0, 0x0, 0x0, 0x68)
        /home/wenyuanhao/goworkspace/src/github.com/CanalSharp/canal-go/vendor/github.com/golang/protobuf/proto/decode.go:336 +0x3b
main.printEntry(0xc42017c000, 0x1b0, 0x266)
        /home/wenyuanhao/goworkspace/src/github.com/CanalSharp/canal-go/samples/main.go:41 +0x149
main.main()
        /home/wenyuanhao/goworkspace/src/github.com/CanalSharp/canal-go/samples/main.go:29 +0x1d9
exit status 2

**Comment by WithLin** [comment]
已经解决
