### ISSUE TITLE
获取不到详细的内容

### ISSUE THREAD

**Issue by wyhisphper** [CanalClient/canal-go#9]
获取不到具体的内容，在sample中直接打印fmt.Println(message.Entries)，获取到的信息是
[{version:1 logfileName:"mysql-bin.000002" logfileOffset:23611 serverId:1 serverenCode:"UTF-8" executeTime:1541055476000 sourceType:MYSQL eventLength:72  0xc42001243c [32 189 45] {} [] 0} {version:1 logfileName:"mysql-bin.000002" logfileOffset:24257 serverId:1 serverenCode:"UTF-8" executeTime:1541055476000 sourceType:MYSQL eventLength:27  0xc42001246c [18 6 51 57 52 56 55 51] {} [] 0}]

相同的canal instance，用java能获取到内容（ 客户端用的是https://github.com/liukelin/canal_mysql_nosql_sync/tree/master/canal-client ），在java连接成功后会有一个log
2018-11-01 15:06:39.566 [New I/O server worker #1-2] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to .*\..*

此时再断开java客户端，运行go客户端，就可以获取到信息，但是重启canal instance后又不行

**Comment by WithLin** [comment]
你直接看一下sample吧？ 不可以直接打印Entries的。你要拿到的是rowchange吧？还有解析rowchange的

**Comment by WithLin** [comment]
不可能吧  我这边跑了50w条数据，全部都拿到了呀。

**Comment by WithLin** [comment]
你的微信多少 我加下您

**Comment by wyhisphper** [comment]
> 你的微信多少 我加下您

thewyh94

**Comment by WithLin** [comment]
已经验证 是您的canal-server的问题。

**Comment by frankling0916** [comment]
我也遇到类似的问题
